#!/bin/sh
commit_msg=$(cat "$1")
pattern="^(feat|fix|infra|docs|refactor|test|chore)(\(.+\))?: .{1,72}"
if ! echo "$commit_msg" | grep -qE "$pattern"; then
  echo "ERROR: Commit message must follow Conventional Commits:"
  echo "  <type>(<scope>): <summary>"
  echo "  Types: feat, fix, infra, docs, refactor, test, chore"
  exit 1
fi
